### ISSUE TITLE
Ovi speed on E (or V) causes slight issue for me

### ISSUE THREAD

**Issue by ezekiel24r** [bobo38/TheCoreLite#24]
I rebound it to 5 for this reason: If you try to spawn some overlords (or mutas with the recent change) when no larva is available, then you will accidentally cause overlord speed to begin research. I felt more comfortable having it on 5 because it ties in with burrow being on 4 as a research hotkey. I imagine if I updated to the new changes I would start making queens accidentally because of them being bound to E.

For clarification:
W(Hatcheries) -> Space(Select Larva) -> (no larva) -> E or V = queen or ovi speed started accidentally.
 

For me this was happening when I was trying to macro out some overlords without looking, I know I could just "play right" and wait for larva to be there, but sometimes in the heat of the moment I just press the keys out of habit. Anyway it's just a small issue that was easy enough to fix on my own.

**Comment by bobo38** [comment]
Thanks for reporting, i will try to look about that

My impression is that with E for queen being used more consistently each game than ovi speed this problem may disappear from itself

**Comment by bobo38** [comment]
fixed with commit 64957c5f1204877621ee9cac37cb049ea786e1bd
