### ISSUE TITLE
Broken Discord invite link

### ISSUE THREAD

**Issue by robamaton** [bobo38/TheCoreLite#27]
When I click the link, I see this:
![screen shot 2018-09-07 at 9 54 44 am](https://user-images.githubusercontent.com/1554017/45223021-14408500-b284-11e8-91db-fc5a50b0690d.png)

 Might need to refresh the invite. Would love to join!

**Comment by bobo38** [comment]
thanks for having reported
it's now fixed! see you soon ;)

**Comment by robamaton** [comment]
Hmm still seems broken to me. It's possible this is on my end. Maybe you can just send me an invite manually? My email is jdsutherland3@gmail.com

**Comment by Gabirel** [comment]
Still expired. Any update for the discord channel link?

**Comment by bobo38** [comment]
thanks for the report, it should be fixed forever (it seems that I found a way to generate no expiration limit links)
