### ISSUE TITLE
Stable vs USQwerty?

### ISSUE THREAD

**Issue by ShadowDancer** [bobo38/TheCoreLite#28]
What's the difference? I have Qwerty keyboard, which one I should use?

**Comment by bobo38** [comment]
stable directory is an attempt to save a reference to catch regression and produce good change log. It's a revision control copy of last reference point to generate [StableRegression.log](https://github.com/bobo38/TheCoreLite/blob/master/StableRegression.log), nothing to use…

You may search for last release:
https://github.com/bobo38/TheCoreLite/releases

The current master branch is pretty solid and already clean against next balance update (Nov 2018). Some changes may occur next week, as I found a motivated TheCore experienced Terran player to go after T optimization

**Comment by ShadowDancer** [comment]
Thanks. I have some feedback (if You need it ;))

 I find TheCoreLite a bit unstable. I trained a bit on lasted release (which has bugs with Tychus commander and caps-lock camera set with `alt`), and then I downloaded latest master and I find everything "upside down", especially no camera on q/w (seems like bug, bound to alt+q bound to ControlGroupAppendAndSteal5), no camera on capslock, Tychus eng bays E (should be 4?), halt moved from b to 4 (idk if Tychus only). and so on.

Also I find core lite a bit cumbersome, because from one side I have beautiful ability and camera keys on qwer rows, but I have to take my fingers off these rows to press ctrl/shift/alt keys. I think (not sure though), that this setup would be much better if I could use my thumb for modifiers (maybe b/n/m with space removed?) and keep my fingers on qwer rows.

**Comment by ShadowDancer** [comment]
Nvm, I got it. I think that new changes are ok, just sucks that they are not release yet and new people download old keys. Coop game hotkeys are broken though.

**Comment by bobo38** [comment]
In case problems come after Blizzard update, I guess users are used to fix them, or to go visit master branch

Releases are for me milestones to:
- clean-up stuff in a consistent way periodically: big overall check in all contexts, documentation content and consistency checks
- communicate in SC2 communities, for the project to be visible (especially appreciated after big patches)
- get a feeling that something move on, the GitHub release section with the condensed change log is rewarding to look

I will piss off a casual coop gamer and check unbounds for coop with last master branch content (not my private customized local copy)

**Comment by bobo38** [comment]
I see no issue with last master content, if you have any please report as a separated issue with some explanation

TheCore Lite is a community based project, with one main developer
my motto are easy going:
- "cross-country casual gamer compatible good enough for all" not "top notch Formula 1 optimization"
- "if you see something wrong, try fix it"
- "if you cannot fix it, report it", if you don't dare, it should not be that critical :D
- "if fixed it, report it", if you don't dare, it should not be that critical :D

**Bug report welcome**
Typically I overlook coop (i don't play it), and Blizzard change stuff that breaks sometimes, issues are there to report something goes wrong and need fix. Suggested fix ideas or pull requests of seed are welcome.

**Enhancement suggestion welcome**
If you find something that makes sense for you you can also file issue to report your wished changes and the reasoning behind it. My goal with coop is to get a quick and dirty fix to fight unbounds, not ultimate optimization of all commanders (i have access to 7 of them fully, have limited interest and don't want to spend money in them)
As an example some Tychus units/buildings' commands sucks, I don't give a shit I have no idea about how the commander is supposed to be played at level 15, but any suggestion is welcome and accepted as long as it doesn't break multiplayer and cause too many conflicts headhaches with campaigns
