### ISSUE TITLE
Dehaka Update Unbound Keys

### ISSUE THREAD

**Issue by DBosley** [bobo38/TheCoreLite#3]
New Dehaka update keybinds need set up.

**Comment by bobo38** [comment]
Thanks for the notice ! I will deal with that

The only problem I see is that Coop Dekara has a huge lot of hotkeys, that does not fit in the TheCoreLite compact scheme. I will release master with most of the keys mapped to something consistent. Feel free to feedback what you would like to see for Dekara's keys according to the most useful features in your view

**Comment by bobo38** [comment]
new master commit with reasonable Coop keys for Dehaka and no unbound warning shown at mission start

**Comment by DBosley** [comment]
Thanks a ton!

**Comment by bobo38** [comment]
I have some doubt about the Drone keys to build the primal heroes' building. Unfortunately there is no graphical way to set those bindkeys. Additionally the larvae bindings should be same for primal zergling/roach/hydralisk/swarm host/ultralisk as for Multiplayer, but not sure
