### ISSUE TITLE
Coop : Missing Refinery binding for Han & Horner commander

### ISSUE THREAD

**Issue by Thuwe** [bobo38/TheCoreLite#30]
For coop commander Han & Horner, Refinery is still bound to R instead of F.

In hotkeys file it seems that the following line is missing : 
"Refinery/HHSCV=F"

I added it by changing the hotkey directly in game.

**Comment by bobo38** [comment]
nice catch!! it seems that basic building and advanced building commands cards are lot of inconsistencies

**Comment by bobo38** [comment]
Thanks for the report as an issue on the repo, I've proceeded with a coop clean-up. More change expected due to Zeratul release
