### ISSUE TITLE
Zeratul Update - Unbound Keys

### ISSUE THREAD

**Issue by JStation** [bobo38/TheCoreLite#33]
Getting an unbound keys warning at start of games since Zeratul co-op commander was released.

**Comment by bobo38** [comment]
I noticed one that was producing no unbound pop-up: "Stasis Beam" from "Artifact Reserve", could you confirm?
I think it cannot be fixed with the GUI, and I found no way to harvest in the game data successfully. JaKaTaK reported it to Blizzard

**Comment by bobo38** [comment]
I've checked today: single Coop unbound is Zeratul "Stasis Beam" from "Artifact Reserve", with unchanged analysis

**Comment by bobo38** [comment]
bug clean-up: no more Zeratul unbound, a Blizzard patch may have fixed it
