### ISSUE TITLE
Question on using the caps lock key

### ISSUE THREAD

**Issue by eric-hu** [bobo38/TheCoreLite#35]
Hi there,

I'm using The Core Lite on both Windows and Mac. On both OSes, I've disabled caps lock, but in Windows I had to use a registry edit to do so. That makes a Caps Lock keypress not register in Starcraft. Is there a way to use Caps Lock in SC2 without turning on and off caps lock mode?

As an aside, thank you for keeping this up to date! I'm still got more to learn with this keyboard layout, but it's already making a big difference in my mechanics.

**Comment by bobo38** [comment]
Thanks for reporting
It could be that Starcraft 2 on Windows is unable to recognised CapsLock as a keyboard event in case of CapsLock is disabled in this way
Have you tried to use the GUI hotkey to fix it? It might be possible that CapsLock keypress with your setup is recognized in-game by another keyboard event

**Comment by eric-hu** [comment]
I don't think I know what the GUI hotkey is, but I'd like to give that a try. Can you give me more information about that?

**Comment by bobo38** [comment]
1. In game: Menu -> Options -> Hotkeys
2. Select your TheCore Lite.SC2Hotkeys (save it if you've customized it)
3. Replace any "CapsLock" occurence with proper keyboard event with your strange setup

If you're using unmodified current TheCore Lite those lines are to be modified
 CameraCenter=Alt+Tab,Alt+CapsLock,Alt+Grave,Alt+Shift
 ControlGroupAppend6=Control+Alt+CapsLock
 ControlGroupAppendAndSteal6=Control+CapsLock
 ControlGroupAssign6=Shift+Alt+CapsLock
 ControlGroupAssignAndSteal6=Control+Shift+CapsLock
 ControlGroupRecall6=CapsLock

Example with "ControlGroupRecall6" to find proper keycode:
-  browse to Global->Control Groups
-  click on "Select Control Group 6"
-  click on "CapsLock" blue box with the cross in upper-right
- next keyboard/mouse event will overwrite "CapsLock"

Maybe CapsLock physical key press with your setup gives a different Starcraft 2 key code. If you get this work, you can change all CapsLock to the proper key code in the .SC2Hotkeys for all occurences

**Comment by eric-hu** [comment]
Ah, I understand what you mean now. This would work for me, but I actually want to use CapsLock so I can stick with the default settings for TheCoreLite. I was just wondering if you have a way on Windows to prevent using the hotkey from toggling between caps and no caps for the system.

**Comment by bobo38** [comment]
I think there are various ways:
https://www.wikihow.com/Disable-the-Capslock-Key-in-Windows
(using regedit or relying on external software)

The point is that you want a "CapsLock" event detected by SC2 at Capslock key press, while "Caps Lock" behavior is inhibited. Maybe there is a setup that would enable that, maybe not.

Unfortunately I cannot help further, as I'm a Linux user, with no Windows at all…

**Comment by eric-hu** [comment]
Thanks for your last reply! Sorry, I thought I had closed this already. I'll share back any findings I have here when I make time to research.

**Comment by bobo38** [comment]
no problem, you're welcome! glhf
