### ISSUE TITLE
Stetmann Hotkeys broken 

### ISSUE THREAD

**Issue by DeadlyKitten37** [bobo38/TheCoreLite#37]
shortly after Stetmann was released blizzard released a 2nd update at which most of the Stetmann hotkeys stopped working (they were either unbound or reset to default) . I also found that when setting a hotkey manually and looking in the .hotkey file the names of the broken hotkeys differed between the new hotkey file and the downloaded hotkey file (For example 'Drone/LarvaStetmann=Space' in the core lite version instead of 'DroneStetmann/LarvaStetmann=Space' when i change the hotkeys in-game). I have been using USQwerty for everything but i believe other keyboards will have the same problem

**Comment by bobo38** [comment]
oh thanks for the report

**Comment by bobo38** [comment]
related to #40

**Comment by bobo38** [comment]
Stetmann is clean on master branch after reuse of pull request #40

**Comment by bobo38** [comment]
useful link for Stetmann's drone building keys (that do not appear in GUI)
https://us.forums.blizzard.com/en/sc2/t/hotkey-assignment-for-stetmanns-drones/339
