### ISSUE TITLE
Stukov buildings are not consistent with terran buildings

### ISSUE THREAD

**Issue by tomekowal** [bobo38/TheCoreLite#4]
Normally terrans have F for refinery, E for CC and so on,
Stukov has R for Refinery, C for CC as if it was copied from Standard.

With some help, I could try to make a PR for the repository :)
Just some pointers: where should I search for Stukov bindings and so on.

Fantastic work BTW, I love the bindings!

**Comment by bobo38** [comment]
You're welcome ! Most of the work is related to TheCore project and JaKaTaK and I maintained and adjusted some stuff here and there with some additional changes

Thanks for the feedback. Refinery/CC/Forge buildings (and respective from other races) got changed in multiplayer recently, out of a suggestion from MilExo on TheCore Lite thread on Teamliquid. Thanks for pointing at this inconsistency: Coop is supported but not under careful consistency check.

I will fix it soon

**Comment by bobo38** [comment]
fixed on master branch, please check if it is ok

**Comment by tomekowal** [comment]
Everything works now for Stukov. Thank you!

**Comment by bobo38** [comment]
have fun !
