### ISSUE TITLE
Unbind DisplayMode

### ISSUE THREAD

**Issue by vadim-tivikov** [bobo38/TheCoreLite#5]
In Standart profile Alt+Enter bind for DisplayMode
`DisplayMode=Alt+Enter`

In TheCoreLite Alt+Enter overridden on ChatIndividual
`ChatIndividual=Alt+Enter`
But for DisplayMode an alternate keyboard shortcut is not offered.

![2017-10-15 15-15-59](https://user-images.githubusercontent.com/16742341/31584702-dacfc46c-b1bb-11e7-91d9-d09acf18b6d8.png)

**Comment by bobo38** [comment]
could you please describe how I could reproduce this unbound? is it happening watching replays?

**Comment by vadim-tivikov** [comment]
For reproduce it is enough to use TheCoreLite, and for fix it - it is enough to define the DisplayMode.
For example:
`DisplayMode=Alt+F12`

**Comment by bobo38** [comment]
![tmp dq53dug9si](https://user-images.githubusercontent.com/17250498/31587315-f0a45496-b1df-11e7-8678-f0deab300b5e.jpg)
It seems that standard  default is Ctrl+Alt+Enter, it's different from the one referenced in the project Defaults.ini file. A smart solution could be to fix the Defaults.ini and regenerate files

I've never seen this unbound before (despite using TheCore Lite ;D), and would be interested in being able to reproduce it

**Comment by bobo38** [comment]
OK I've understood: I use TheCore Lite.SC2Hotkeys seed at the root of the project (too test changes on the fly before releasing them), not the USQwerty one!

**Comment by bobo38** [comment]
thanks a lot for the issue report… I will modify my check of TheCoreLite in game with a dev file and a pushed file, so that I can catch such inconsistencies more easily
