### ISSUE TITLE
Keys for Protoss Ground Armor and Shield Upgrade

### ISSUE THREAD

**Issue by nicball** [bobo38/TheCoreLite#50]
It is common among the 3 races that Ground Weapon upgrade is assigned to (D) and Ground Armor to (Space). However, Protoss often prefer Shields upgrade over Ground Armor (Am I right?). Wonder if it is more sensible to swap these keys?

**Comment by bobo38** [comment]
Sorry for late answer: i won't change anything to TheCore Lite, it's kind of (laggy) maintenance state. Nevertheless it's a good baseline if you want to experiment and tune. Feel free to be creative

Thanks
