### ISSUE TITLE
Hotkey issue with Abathur P2 Swarm Host Deep Tunnel and Fix 

### ISSUE THREAD

**Issue by aymebour** [bobo38/TheCoreLite#53]
Hello,

I found a bug with the deep tunnel keys of Abathur Swarm Host in coop (follow the link). To fix that add the following line in the shortcut files :

BrutaliskDeepTunnel/SwarmHost=C
BrutaliskDeepTunnel/SwarmHostBurrowed=C

[https://us.forums.blizzard.com/en/sc2/t/hotkey-issue-with-abathur-p2-swarm-host-deep-tunnel-and-fix/26381](https://us.forums.blizzard.com/en/sc2/t/hotkey-issue-with-abathur-p2-swarm-host-deep-tunnel-and-fix/26381)

**Comment by bobo38** [comment]
hello, thanks for reporting, I will add that
